# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service/grpc/llm/llm.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aservice/grpc/llm/llm.proto\x12\x0bservice.llm\"\x0e\n\x0cPromptConfig\"W\n\rPromptRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12)\n\x06\x63onfig\x18\x03 \x01(\x0b\x32\x19.service.llm.PromptConfig\"\xca\x01\n\x0ePromptMetaData\x12\x19\n\x11tokens_per_second\x18\x01 \x01(\x02\x12\x1a\n\x12\x61verage_batch_size\x18\x02 \x01(\x02\x12\x30\n\x05model\x18\x03 \x01(\x0b\x32!.service.llm.PromptMetaData.Model\x1aO\n\x05Model\x12\x0e\n\x06\x64\x65vice\x18\x01 \x01(\t\x12\r\n\x05\x64type\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x19\n\x11number_of_devices\x18\x04 \x01(\x05\"\x9c\x01\n\x0bPromptReply\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x1a\n\x12is_end_of_sequence\x18\x03 \x01(\x08\x12)\n\x06\x63onfig\x18\x04 \x01(\x0b\x32\x19.service.llm.PromptConfig\x12)\n\x04meta\x18\x05 \x01(\x0b\x32\x1b.service.llm.PromptMetaData2G\n\x03Llm\x12@\n\x06prompt\x12\x1a.service.llm.PromptRequest\x1a\x18.service.llm.PromptReply0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service.grpc.llm.llm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROMPTCONFIG']._serialized_start=43
  _globals['_PROMPTCONFIG']._serialized_end=57
  _globals['_PROMPTREQUEST']._serialized_start=59
  _globals['_PROMPTREQUEST']._serialized_end=146
  _globals['_PROMPTMETADATA']._serialized_start=149
  _globals['_PROMPTMETADATA']._serialized_end=351
  _globals['_PROMPTMETADATA_MODEL']._serialized_start=272
  _globals['_PROMPTMETADATA_MODEL']._serialized_end=351
  _globals['_PROMPTREPLY']._serialized_start=354
  _globals['_PROMPTREPLY']._serialized_end=510
  _globals['_LLM']._serialized_start=512
  _globals['_LLM']._serialized_end=583
# @@protoc_insertion_point(module_scope)
