// This file is @generated by prost-build.
pub mod v1 {
    pub mod llm {
        pub mod service {
            include!("v1.llm.service.rs");
        }
    }
    pub mod prompt {
        pub mod service {
            include!("v1.prompt.service.rs");
        }
    }
}
